### ISSUE TITLE
Some +3 .dsk don't load if they use more than 40 tracks

### ISSUE THREAD

**Issue by zzedmore** [libretro/fuse-libretro#102]
Some Spectrum +3 games use more than 40 tracks (Sword of Ianna etc.). These don't boot. We need an option to change '`+3 Drive A`' to '`Double-sided 80 track`'.

**Comment by zzedmore** [comment]
@tomconte Maybe Drive A should be permanently changed to 'Double-sided 80 track' as there is only one drive available in this core anyway. I don't think there's any reason to keep 40 track drive ?

**Comment by tomconte** [comment]
Right, ideally we would implement all these options like the real Fuse does but it's a lot of work :-)

I don't want to permanently change the standard Spectrum +3 drive type because I don't what side effects that could have... But I could make a special case, and change the drive type on the fly if I detect that the disk image has more than 40 tracks.

I am testing with Sword of Ianna, do you have any other examples by any chance?

**Comment by zzedmore** [comment]
I can't recall what they were to be honest! They were compilations from somewhere but can't remember which ones.

**Comment by tomconte** [comment]
I have merge the fix, it should fix the problem with Sword of Ianna.

**Comment by zzedmore** [comment]
Working great! Thanks a lot @tomconte This actually makes it better than regular FUSE because of the autodetect. Hopefully you can implement the autostart toggle ?
