### ISSUE TITLE
Please add .rzx format and question about other formats.

### ISSUE THREAD

**Issue by windale** [libretro/fuse-libretro#13]
Hi, could you please add .RZX format please ? This allows us to watch Replays of games being completed (rzxarchive.co.uk).

Could you also add a pause button that DOESN'T add anything on the screen (like a menu) so we can pause and read RZX text adventures that skip too fast to read.

Also, what about .TRD and .SCL formats (Pentagon etc.). These have some great demos. I know you need extra roms but they are easily obtainable and we could add them to the BIOS folder like other systems do.

**Comment by leiradel** [comment]
Hey,

Pause button: Just press "P".

TRD & SCL: I'll need to bake the extra roms into the core, and add core options to enable/disable them, so allow me some time to add these.

RZX: Do replays found on the Internet include the game's snapshot? If they don't, the core will fail to load the game.

**Comment by leiradel** [comment]
I've added RZX as a valid Fuse core extension and it works as expected with a .rzx file downloaded from RZX Archive.

If the RZX file doesn't contain a snapshot of the game, the core will *not* play the recording since it won't be able to load the game from the file system.

I'm closing this issue and will create two others for the TRD and SCL extensions.
