### ISSUE TITLE
Fuse core for WII U crashes after selecting joystick, and no on-screen keyboard.

### ISSUE THREAD

**Issue by mnx-xx** [libretro/fuse-libretro#138]
As I write in title, after selecting joystick from Controls menu for Port 1 (Kempston, Cursor or so)  and returning to game, Retroarch completely freezes, and WII U must be hard shut down to restart.
Also, on-screen keyboard over the defined key (- in menu, but also any other defined) does not work. It shows nothing.
It's the same for both stable and latest night-builds.
![IMG_20221030_073505](https://user-images.githubusercontent.com/581911/199057722-f635fbb0-85b7-4a26-9a26-a5179e1330a2.jpg)

**Comment by Ploggy** [comment]
Try to consolidate the issues
these are all the same issue
https://github.com/libretro/fuse-libretro/issues/121
https://github.com/libretro/fuse-libretro/issues/124

**Comment by filobeddo** [comment]
Hi. Just to add a clue to the cause of this issue which may assist.

I am aware that this was a problem which started after a certain update; since I used to be able to use WiiU/RetroArch/Fuse core with no issues.

I've just gone back to discover exactly when this was; by restoring old Fuse cores.
I've found that the break occurred after v1.9.14, e.g. that works fine and then if you use  >= v1.10.0 then this crash will occur when trying to make any config change around input.

Hopefully this will be of use in going back to compare the differences in WiiU/Fuse after v1.9.14.

Regards,

Simon.
