### ISSUE TITLE
SCL auto-boot and keyboard issues

### ISSUE THREAD

**Issue by windale** [libretro/fuse-libretro#24]
You closed my last issue before I could reply so I had to open another one.

You say I have to create an auto-boot manually for every game ?!? Other Spectrum emulators can auto-boot them fine. Is it not possible for you to implement this or you're not sure how ?

My physical keyboard already works but in TRDOS the Q and W keys don't work for some reason. This makes typing some filenames in to "manually" boot impossible. The virtual keyboard only allows numbers and lower case letters because the CapShift key doesn't work. This means I can't type the Case Sensitive filenames.

If you don't know how to implement an auto-boot like other Spectrum emulators do, can you add a toggle for the Capshift and Symbol Shift keys on the virtual keyboard so I can type capital letters please ?

I will see if the Q and W keys work on the non-RetroArch version of Fuse.

EDIT:  The Q and W keys work fine on my keyboard in the regular version of Fuse.

**Comment by leiradel** [comment]
I closed the other issue because it was about TRD and SCL files not working, and they were.

This issue has two different subjects. Ideally we take care of only one problem per issue to properly manage bugs and feature requests.

Anyway, I've tried a couple of games with Fuse and it doesn't start them automatically. Fire & Ice (http://www.worldofspectrum.org/infoseekid.cgi?id=0015215) does autoboot to a file manager UI of sorts, but then you have to select the file you want to execute to play the game.

Viking Quest 1 (http://tarjan.uw.hu/zx_gamez_downloadz.htm) doesn't autoboot to anything and just leaves you at the TR-DOS prompt. You have to manually run the V_Quest1 file to execute the game.

As for the keyboard, RetroArch uses some keys as shortcuts to some of its functionalities, and also some keys are bound to the RetroPad virtual controller. To have the entire keyboard available to the emulator, you have to configure RetroArch to use a hotkey for its shortcuts. Please check the RetroArch documentation for instructions on how to do that.

I'll leave this issue open for some time waiting for your feedback about autoboot. If you find a TRD or SCL file that autoboots into the game with Fuse and does not do that with RetroArch + fuse-libretro please comment it here.

**Comment by leiradel** [comment]
I forgot one thing: the virtual keyboard should treat the shift keys as toggle keys, so I'll open a bug to fix that.

**Comment by windale** [comment]
So is there no chance of you making lr-fuse better than regular fuse by making SCL files auto-boot ?

I just tried a couple of text adventures (Hunchback & Neverending Story) and the Q and W keys work. So why don't they work in TRDOS ? All keys work fine all the time in regular Fuse.

**Comment by leiradel** [comment]
If the SCL or TRD disk image has more than one executable file, which one should be run? If there's a boot file (which is automatically executed by TR-DOS), should we let it run (it can load something other than the game, i.e. Fire & Ice) or should we run a different file? Which one?

As you can see, it's not possible to correctly autoboot files in all the cases. The only reliable way to do that is if the disk image has only one executable file. The effort is too much for too litle benefit, since only a fraction of the images would correctly autoboot.

The best thing to do is to customize your disk images and add a boot file that will execute the correct file to start the game.

Keyboard: again, you have to configure the hotkey (AKA escape key) in RetroArch. The Fuse core doesn't even receive some keystrokes if you fail to properly configure RetroArch in that regard.

I'll close this issue. If you still have problems with the keyboard after configuring RetroArch, please reopen this issue or open another issue just for that. Please test with other cores that have keyboards first, i.e. a MSX core, to make sure it's a problem only with the Fuse core.

**Comment by windale** [comment]
Please stop closing these threads, I had something else to report on this.
