### ISSUE TITLE
Fuse 1.3.4 update ?

### ISSUE THREAD

**Issue by ghost** [libretro/fuse-libretro#33]
Is there going to be an update from the new Fuse 1.2 release ? I also noticed that the real time tape loading option doesn't work.

**Comment by leiradel** [comment]
Tape loading is working just fine afaik. Is the problematic tape available for download so I can test it?

Wrt Fuse 1.2, I'll need some time to make the upgrade.

**Comment by windale** [comment]
I meant when turning OFF fast loading, it still loads fast, it should be loading at normal speed with loading sound.

**Comment by leiradel** [comment]
Yeah, slow tape loading seems a bit "iffy". I could make it work but not everytime. I'll take a look.

I'll take a look at Spectacol, we can have another ZX Spectrum core if it's easy to port. Thanks for the suggestion.

**Comment by leiradel** [comment]
@windale I can't seem to find Spectacol's source code, is it open source? Do you have a link?

**Comment by windale** [comment]
It's currently on Android.

https://github.com/bog-dan-ro/spectacol

**Comment by leiradel** [comment]
Hm, so I don't see the point in porting Spectacol to libretro.

One of the goals when porting an emulator to libretro is to completely remove its UI, since all settings and game browsing is the front-end (i.e. RetroArch) responsibility. Since Spectacol is Fuse with a QML UI, removing the UI will result in a port very similar, if not equal, to fuse-libretro.

Spectacol begin based on Fuse 1.2 is not a good reason to use it for the libretro port, since I can just grab Fuse 1.2 myself and upgrade fuse-libretro. Are you hitting a Fuse 1.1.1 bug that the 1.2 version solves? 

Regarding the on-screen keyboard, I'll take a look and see what it does that is better than the fuse-libretro one and try to implement them, but only if it's a really killer feature because there's some discussion in libretro about a more flexible input mapping that will make on-screen keyboards useless.

**Comment by windale** [comment]
You know more about this than me, whatever you think is best, although I would like to see the 3 different loader acceleration options (Turbo, Safe & None). This helps with some problematic protection loaders that don't load when on full turbo loading. And the Spectacol on-screen keyboard has toggle Capshift/Symbol shift (which doesn't work on lr-fuse). Fuse 1.2 has probably increased overall compatibility otherwise they wouldn't have released it.

**Comment by leiradel** [comment]
What are the command-line options and/or in-app settings for the loading acceleration options? I need it to expose them as core options to the front-end.

**Comment by windale** [comment]
![screenshot_2016-06-13-16-24-30](https://cloud.githubusercontent.com/assets/12862298/16012916/67a5a876-3183-11e6-93cc-ab2c2fe7f500.png)

**Comment by leiradel** [comment]
Ok, thanks. I'll try to find how Spectacol maps those options to Fuse.

**Comment by windale** [comment]
Any chance of updating this Libretro port to the latest version ? You didn't bother last time but now several improvements have been made including SCL and TRD autobboot. They are also adding compatibility for the Recreated ZX Spectrum keyboard. Any chance you could update this ?

**Comment by leiradel** [comment]
I'll take a stab at it this weekend.

**Comment by leiradel** [comment]
The `specplus3_disk_writeprotect` function is defined in a header but not implemented anywhere. The 1.2.2 source code is a little strange. I'll wait for another minor version bump.

**Comment by windale** [comment]
Still no update then ? :(

The RetroPie team have updated the regular Fuse to 1.3.0 which has TRDOS images autoboot and recreated ZX Spectrum keyboard support and improved compatibility etc. It would be great if you could update lr-fuse 1.1 to the latest version so we can use shaders and better joystick support. Thanks.

**Comment by leiradel** [comment]
It's easy to update when all you must do is build the emulator. The libretro port is more intrusive, because it has to conform to the libretro API. Due to some more pressing matters, expect an update only for 2017, unfortunately.

**Comment by blinkydoos** [comment]
Is there any chance this could be updated ? I see it was originally asked over a year ago. :-(

**Comment by leiradel** [comment]
It will, as time permits.

**Comment by telanus** [comment]
See 1.5.0 is out, any idea when an update will appear?

**Comment by SaucySarah** [comment]
Nearly 2 years after the OP, any chance of an update to the latest version ? lol.

**Comment by telanus** [comment]
@SaucySarah I know https://www.reddit.com/user/DanteAlighieri64said that @leiradel was looking into it. It's up to leiradel to find time to update it. I hope it'll hapen before the next ice age.

**Comment by snoofly** [comment]
Would love to see an update of lr-fuse from old 1.1.1 version now many enhancements/fixes for outstanding issues appear addressed in the latest fuse base so just adding my comment in case it can motivate those more able than me.

**Comment by Gazdaman** [comment]
@leiradel Just wondering if I started a bounty to update this core, would it help inspire you to update the core to the latest Fuse version?
(1.5.7 at time of writing)
I'd be happy to kick off a bounty for this if you are up for it?
Hope you can give feedback one way or another, cheers

**Comment by leiradel** [comment]
Sorry, I can't work with it right now because of my current contract.

**Comment by Volutar** [comment]
Well, it seems this zx core, the only one which was(is) integrated into retroarch, is better to be considered obsolete, or even “closed”, and not listed as “supported”. Simply not to give people any hope and don’t make them hold their breaths. And to mark zx libretro core as “vacant”, so maybe someone will make another libretro zx core.

**Comment by Gazdaman** [comment]
I've started a bounty for updating the core.
Link is below for anyone who is interested in working on the bounty or supporting it:
https://github.com/libretro/fuse-libretro/issues/87

**Comment by tomconte** [comment]
I have opened a pull request to update this core to Fuse 1.6.0 and lib spectrum 1.5.0: #89. Hopefully it should fix a few of the issues mentioned here. 

Comments/reviews welcome!
